
/**
 * Generates and triggers a download for a standalone HTML version of the report.
 * This creates a full HTML5 document with embedded styles and external CDN links
 * so the report looks identical to the app version when opened locally.
 * 
 * @param elementId The ID of the HTML element containing the report content.
 * @param fileName The desired name for the downloaded file.
 */
export const downloadAsHtml = (elementId: string, fileName: string): void => {
  const reportElement = document.getElementById(elementId);
  if (!reportElement) {
    console.error('Report content element not found');
    return;
  }

  // Clone the content to avoid modifying the live DOM
  const content = reportElement.innerHTML;
  
  // Construct a full, valid HTML document
  const fullHtml = `
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${fileName.replace('.html', '').replace(/_/g, ' ')}</title>
    <!-- Use Tailwind CDN for instant styling -->
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        body { 
            font-family: 'Inter', sans-serif; 
            -webkit-print-color-adjust: exact; 
            line-height: 1.6;
            color: #1e293b;
        }
        @media print {
            .no-print { display: none !important; }
            body { background-color: white !important; padding: 0 !important; }
            .report-card { box-shadow: none !important; border: none !important; width: 100% !important; max-width: none !important; margin: 0 !important; padding: 0 !important; }
            /* Force background colors to print */
            * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
        }

        /* Enhanced Content Styling */
        h1, h2, h3, h4 { color: #0f172a; font-weight: 800; margin-top: 1.5em; margin-bottom: 0.75em; }
        h1 { font-size: 2.5rem; letter-spacing: -0.025em; }
        h2 { font-size: 1.8rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; color: #1e293b; }
        h3 { font-size: 1.4rem; color: #334155; }
        
        p { margin-bottom: 1.25rem; leading-relaxed; }
        strong { font-weight: 700; color: #0f172a; }
        
        ul, ol { margin-bottom: 1.5rem; padding-left: 1.5rem; }
        ul { list-style-type: disc; }
        ol { list-style-type: decimal; }
        li { margin-bottom: 0.5rem; }
        
        blockquote { 
            border-left: 4px solid #6366f1; 
            background-color: #f8fafc; 
            padding: 1rem 1.5rem;
            font-style: italic;
            margin: 1.5rem 0;
            border-radius: 0 0.5rem 0.5rem 0;
            color: #475569;
        }

        a { color: #4f46e5; text-decoration: underline; text-underline-offset: 2px; font-weight: 500; }
        a:hover { color: #4338ca; }

        /* Professional Tables */
        table { border-collapse: collapse; width: 100%; margin: 1.5rem 0; font-size: 0.9rem; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border-radius: 0.5rem; overflow: hidden; }
        th, td { border: 1px solid #cbd5e1; padding: 0.75rem 1rem; text-align: left; }
        th { background-color: #f1f5f9; font-weight: 700; color: #334155; text-transform: uppercase; font-size: 0.75rem; letter-spacing: 0.05em; }
        tr:nth-child(even) { background-color: #f8fafc; }
        tr:hover { background-color: #f1f5f9; }

        .break-after-page { page-break-after: always; }
        
        /* Custom scrollbar */
        ::-webkit-scrollbar { width: 8px; }
        ::-webkit-scrollbar-track { background: #f1f1f1; }
        ::-webkit-scrollbar-thumb { background: #94a3b8; border-radius: 4px; }
        ::-webkit-scrollbar-thumb:hover { background: #64748b; }
    </style>
</head>
<body class="bg-slate-50 text-slate-900 py-12 px-4 md:px-8">
    <div class="report-card max-w-4xl mx-auto bg-white rounded-2xl shadow-xl border border-slate-200 overflow-hidden">
        <!-- Header Branding (Optional, matching app header) -->
        <div class="bg-slate-900 text-white p-8 text-center">
            <h1 class="text-3xl font-bold">Emigration Pro Report</h1>
            <p class="text-slate-400 mt-2">Personalized Analysis & Relocation Strategy</p>
        </div>

        <div class="p-8 md:p-16">
            ${content}
            
            <footer class="mt-16 pt-8 border-t border-slate-200 text-center text-slate-400 text-sm">
                <p class="font-semibold text-slate-600">Generated by Emigration Pro Report Generator</p>
                <p class="mt-2">© ${new Date().getFullYear()} Cleer Products</p>
            </footer>
        </div>
    </div>

    <!-- Floating Print Button for UX -->
    <div class="fixed bottom-8 right-8 no-print flex gap-3">
        <button onclick="window.print()" class="flex items-center gap-2 bg-indigo-600 text-white font-bold py-3 px-6 rounded-full shadow-2xl hover:bg-indigo-700 transition-all hover:scale-105 active:scale-95">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2-2v4h10z" />
            </svg>
            Print Report
        </button>
        <button onclick="window.scrollTo({top: 0, behavior: 'smooth'})" class="p-3 bg-white text-slate-600 rounded-full shadow-lg border border-slate-200 hover:bg-slate-50 transition-colors" title="Back to top">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 10l7-7m0 0l7 7m-7-7v18" />
            </svg>
        </button>
    </div>
</body>
</html>
  `;

  const blob = new Blob([fullHtml.trim()], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
