export interface GlossaryTerm {
  term: string;
  category: 'Visas & residency' | 'Documents & applications' | 'U.S. tax & reporting' | 'Healthcare & benefits' | 'Moving & arrival';
  definition: string;
  significance: string;
  example: string;
  source: { label: string; url: string };
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    term: 'Apostille',
    category: 'Documents & applications',
    definition: 'An apostille is a certificate that authenticates the origin of a public document for use in another country that participates in the Hague Apostille Convention.',
    significance: 'A destination authority may require an apostille on a birth certificate, marriage certificate, diploma, or background check before accepting it.',
    example: 'A U.S. birth certificate requested for a residence application may need an apostille from the competent authority in the state that issued it.',
    source: { label: 'U.S. Department of State — Document Authentication', url: 'https://travel.state.gov/content/travel/en/replace-certify-docs/authenticate-your-document.html' },
  },
  {
    term: 'Certified translation',
    category: 'Documents & applications',
    definition: 'A certified translation is a translated document accompanied by a statement from a qualified translator attesting that the translation is complete and accurate.',
    significance: 'Immigration authorities commonly specify the accepted language, translator qualifications, certification wording, and whether notarization is also required.',
    example: 'A destination consulate may require a Spanish translation of an English-language criminal-record certificate by an approved or sworn translator.',
    source: { label: 'USCIS — Tips for Filing Forms by Mail', url: 'https://www.uscis.gov/forms/filing-guidance/tips-for-filing-forms-by-mail' },
  },
  {
    term: 'Criminal-record certificate',
    category: 'Documents & applications',
    definition: 'A criminal-record certificate reports whether a person has a record in the jurisdiction that performed the search; it may also be called a police certificate or background check.',
    significance: 'Residence applications may require federal, state, and foreign certificates covering specified places and periods, often with strict issue-date rules.',
    example: 'An American who previously lived in several countries may need an FBI identity-history summary plus certificates from former countries of residence.',
    source: { label: 'FBI — Identity History Summary Checks', url: 'https://www.fbi.gov/how-we-can-help-you/more-fbi-services-and-information/identity-history-summary-checks' },
  },
  {
    term: 'Proof of accommodation',
    category: 'Documents & applications',
    definition: 'Proof of accommodation is evidence showing where an applicant will stay, such as a lease, property deed, hotel booking, or legally sufficient host declaration.',
    significance: 'The acceptable document and required duration vary by country and visa; a cancellable hotel reservation may not satisfy a residence application.',
    example: 'A consulate may request a registered lease covering the applicant’s planned residence period rather than a short tourist booking.',
    source: { label: 'European Commission — EU Immigration Portal', url: 'https://immigration-portal.ec.europa.eu/index_en' },
  },
  {
    term: 'Proof of financial means',
    category: 'Documents & applications',
    definition: 'Proof of financial means is evidence that an applicant has enough reliable income, savings, or sponsorship to live without prohibited work or public assistance.',
    significance: 'Authorities may define a minimum amount, permitted income sources, statement period, currency conversion method, and family-member increment.',
    example: 'A passive-income applicant may need recent bank statements and evidence that pension or rental income will continue after relocation.',
    source: { label: 'European Commission — EU Immigration Portal', url: 'https://immigration-portal.ec.europa.eu/index_en' },
  },
  {
    term: 'Consular processing',
    category: 'Documents & applications',
    definition: 'Consular processing means applying through an embassy or consulate, usually in the applicant’s country of citizenship or lawful residence, before traveling.',
    significance: 'The correct post, appointment system, jurisdiction rules, interview requirements, and passport-retention period can affect the relocation timeline.',
    example: 'A long-stay visa may have to be approved by the destination country’s consulate before the applicant can enter and obtain a local residence card.',
    source: { label: 'U.S. Department of State — Visa Glossary', url: 'https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/glossary.html' },
  },
  {
    term: 'Visa-free stay',
    category: 'Visas & residency',
    definition: 'A visa-free stay permits short entry without obtaining a visa in advance, subject to limits on duration, purpose, passport validity, and permitted activities.',
    significance: 'Visa-free admission normally does not create residence or unrestricted work rights, and overstaying can affect future travel or immigration applications.',
    example: 'A U.S. visitor may enter part of Europe for a limited tourist stay but still need a national visa or permit to live or work there long term.',
    source: { label: 'European Union — Schengen Area', url: 'https://home-affairs.ec.europa.eu/policies/schengen-borders-and-visa/schengen-area_en' },
  },
  {
    term: 'Temporary residence',
    category: 'Visas & residency',
    definition: 'Temporary residence is permission to live in a country for a limited period under stated conditions, usually with renewal and continued-eligibility requirements.',
    significance: 'The permit may restrict employment, time outside the country, access to public benefits, family sponsorship, and the path toward permanent status.',
    example: 'A renewable one-year permit may require the holder to maintain qualifying income, insurance, accommodation, and a clean record.',
    source: { label: 'European Commission — EU Immigration Portal', url: 'https://immigration-portal.ec.europa.eu/index_en' },
  },
  {
    term: 'Permanent residence',
    category: 'Visas & residency',
    definition: 'Permanent residence is an immigration status allowing indefinite residence, although the card may expire and the status may be lost after extended absence or other disqualifying events.',
    significance: 'Permanent residence often provides greater stability and work access than a temporary permit, but it is not the same as citizenship.',
    example: 'A resident may become eligible after a specified number of lawful years while meeting continuity, income, language, or integration rules.',
    source: { label: 'European Commission — Long-term Residents', url: 'https://home-affairs.ec.europa.eu/policies/migration-and-asylum/legal-migration-and-integration/long-term-residents_en' },
  },
  {
    term: 'Digital nomad visa',
    category: 'Visas & residency',
    definition: 'A digital nomad visa is a country-specific route intended for eligible remote workers who earn from employers or clients outside the destination country.',
    significance: 'Rules differ on minimum income, local clients, employment classification, tax residence, family members, insurance, and renewal.',
    example: 'A remote employee may qualify while a freelancer serving local customers may not, even when both work online.',
    source: { label: 'European Commission — EU Immigration Portal', url: 'https://immigration-portal.ec.europa.eu/index_en' },
  },
  {
    term: 'Passive-income visa',
    category: 'Visas & residency',
    definition: 'A passive-income visa is an informal label for a residence route based primarily on stable non-employment income such as pensions, investments, or rent.',
    significance: '“Passive income” is not a universal legal category; each country decides which income sources count and whether work is allowed.',
    example: 'One country may accept pension and rental income but exclude savings withdrawals or newly established business revenue.',
    source: { label: 'European Commission — EU Immigration Portal', url: 'https://immigration-portal.ec.europa.eu/index_en' },
  },
  {
    term: 'Non-lucrative visa',
    category: 'Visas & residency',
    definition: 'A non-lucrative visa is a residence route that requires sufficient financial support while restricting or prohibiting work under the terms of that status.',
    significance: 'Applicants must confirm whether remote work, self-employment, or later modification to a work-authorized status is permitted.',
    example: 'A retiree living on a pension may fit a route that would be unsuitable for a person who must continue working online.',
    source: { label: 'European Commission — EU Immigration Portal', url: 'https://immigration-portal.ec.europa.eu/index_en' },
  },
  {
    term: 'Family reunification',
    category: 'Visas & residency',
    definition: 'Family reunification is a legal process through which a qualifying resident or citizen seeks permission for specified family members to join or remain with them.',
    significance: 'Eligible relationships, income, housing, insurance, custody documents, work rights, and waiting periods vary by jurisdiction.',
    example: 'A principal resident may need to prove adequate housing and income before a spouse or dependent child receives a permit.',
    source: { label: 'European Commission — Family Reunification', url: 'https://home-affairs.ec.europa.eu/policies/migration-and-asylum/legal-migration-and-integration/family-reunification_en' },
  },
  {
    term: 'Right to work',
    category: 'Visas & residency',
    definition: 'The right to work is legal authorization to perform employment or self-employment; it is separate from permission to enter or reside unless the status expressly combines them.',
    significance: 'A permit may allow employment only for a named employer, occupation, region, number of hours, or type of economic activity.',
    example: 'A dependent spouse may have residence permission but need separate authorization before starting local employment.',
    source: { label: 'European Commission — EU Immigration Portal', url: 'https://immigration-portal.ec.europa.eu/index_en' },
  },
  {
    term: 'Schengen Area',
    category: 'Visas & residency',
    definition: 'The Schengen Area is a group of European countries that generally removed checks at their shared internal borders while applying common external-border rules.',
    significance: 'Schengen short-stay calculations and national residence rules are related but not interchangeable; residence in one country does not automatically grant residence in another.',
    example: 'Time spent visiting several Schengen countries can count toward one shared short-stay limit.',
    source: { label: 'European Union — Schengen Area', url: 'https://home-affairs.ec.europa.eu/policies/schengen-borders-and-visa/schengen-area_en' },
  },
  {
    term: 'Tax residence',
    category: 'U.S. tax & reporting',
    definition: 'Tax residence identifies the jurisdiction that treats a person as resident for tax purposes under domestic law and, where applicable, treaty tie-breaker rules.',
    significance: 'Tax residence is distinct from citizenship and immigration status and may determine whether worldwide income is reportable in a destination country.',
    example: 'A person can remain a U.S. taxpayer while also becoming tax resident in another country, requiring coordinated filings and relief from double taxation.',
    source: { label: 'IRS — Taxpayers Living Abroad', url: 'https://www.irs.gov/individuals/international-taxpayers/taxpayers-living-abroad' },
  },
  {
    term: 'Foreign Earned Income Exclusion (FEIE)',
    category: 'U.S. tax & reporting',
    definition: 'The FEIE is a U.S. federal tax provision that may allow a qualifying taxpayer abroad to exclude a limited amount of foreign earned income from U.S. taxable income.',
    significance: 'It is not automatic, does not cover every income type or every tax, and depends on a foreign tax home plus a qualifying residence or physical-presence test.',
    example: 'Eligible salary or self-employment income may qualify, while pension and investment income generally do not count as earned income for this exclusion.',
    source: { label: 'IRS — Foreign Earned Income Exclusion', url: 'https://www.irs.gov/individuals/international-taxpayers/foreign-earned-income-exclusion' },
  },
  {
    term: 'Foreign Tax Credit',
    category: 'U.S. tax & reporting',
    definition: 'The Foreign Tax Credit may reduce U.S. income tax when a taxpayer pays or accrues qualifying income tax to a foreign country or U.S. possession.',
    significance: 'Creditability, income categories, sourcing, carryovers, and interaction with exclusions require careful calculation.',
    example: 'A U.S. citizen paying qualifying destination-country income tax may be able to claim a U.S. credit, subject to the credit limitation.',
    source: { label: 'IRS — Foreign Tax Credit', url: 'https://www.irs.gov/individuals/international-taxpayers/foreign-tax-credit' },
  },
  {
    term: 'FBAR',
    category: 'U.S. tax & reporting',
    definition: 'The FBAR is an electronic report of qualifying foreign financial accounts filed with the Financial Crimes Enforcement Network, separate from an income-tax return.',
    significance: 'A U.S. person generally evaluates the aggregate maximum value of foreign accounts against the filing threshold, including some accounts with signature authority.',
    example: 'Several individually modest foreign accounts can trigger reporting when their combined maximum values exceed the applicable threshold.',
    source: { label: 'FinCEN — Report of Foreign Bank and Financial Accounts', url: 'https://www.fincen.gov/report-foreign-bank-and-financial-accounts' },
  },
  {
    term: 'FATCA reporting',
    category: 'U.S. tax & reporting',
    definition: 'FATCA is a U.S. reporting framework that can require specified taxpayers to disclose certain foreign financial assets and requires many foreign financial institutions to report U.S.-linked accounts.',
    significance: 'Individual Form 8938 obligations are separate from FBAR rules, with different thresholds, assets, filing destinations, and exceptions.',
    example: 'A taxpayer abroad may need both Form 8938 with the tax return and a separate FBAR when both sets of requirements are met.',
    source: { label: 'IRS — FATCA Information for Individuals', url: 'https://www.irs.gov/businesses/corporations/foreign-account-tax-compliance-act-fatca' },
  },
  {
    term: 'Tax treaty',
    category: 'U.S. tax & reporting',
    definition: 'A tax treaty is an agreement allocating taxing rights and providing rules intended to reduce double taxation and resolve certain cross-border tax conflicts.',
    significance: 'Treaty coverage and benefits depend on the countries, income type, residence, saving clause, limitation provisions, and required disclosures.',
    example: 'A treaty may assign primary taxing rights over a pension or provide a credit mechanism, but the exact article and taxpayer facts control.',
    source: { label: 'IRS — United States Income Tax Treaties', url: 'https://www.irs.gov/businesses/international-businesses/united-states-income-tax-treaties-a-to-z' },
  },
  {
    term: 'Totalization agreement',
    category: 'Healthcare & benefits',
    definition: 'A totalization agreement coordinates U.S. Social Security coverage with another country’s social-insurance system to help avoid dual contributions and protect benefit eligibility.',
    significance: 'The applicable agreement can determine where a cross-border worker contributes and whether periods of coverage can be combined for benefit qualification.',
    example: 'A temporarily transferred employee may remain covered by one country’s system when a certificate of coverage establishes the exemption.',
    source: { label: 'Social Security Administration — International Agreements', url: 'https://www.ssa.gov/international/agreements_overview.html' },
  },
  {
    term: 'International health insurance',
    category: 'Healthcare & benefits',
    definition: 'International health insurance is private medical coverage designed for people living across borders, often with geographic networks, exclusions, deductibles, and evacuation options.',
    significance: 'Travel insurance is usually designed for temporary emergencies and may not satisfy a residence permit or provide continuing routine care.',
    example: 'A new resident may need a policy that explicitly covers the destination, pre-existing conditions as stated, hospitalization, and the full visa period.',
    source: { label: 'U.S. Department of State — Insurance Providers for Overseas Coverage', url: 'https://travel.state.gov/content/travel/en/international-travel/before-you-go/your-health-abroad/insurance-providers-overseas-coverage.html' },
  },
  {
    term: 'Customs declaration',
    category: 'Moving & arrival',
    definition: 'A customs declaration is the formal disclosure of goods, currency, or other controlled items being imported or exported, whether carried personally or shipped separately.',
    significance: 'Thresholds, prohibited goods, valuation, documentation, inspections, duties, and declaration channels are set by the relevant country.',
    example: 'A traveler may need to declare currency above a threshold or provide an inventory for household goods arriving later by freight.',
    source: { label: 'U.S. Customs and Border Protection — Know Before You Go', url: 'https://www.cbp.gov/travel/us-citizens/know-before-you-go' },
  },
  {
    term: 'Naturalization',
    category: 'Moving & arrival',
    definition: 'Naturalization is the legal process by which a person who was not a citizen at birth acquires citizenship after meeting the destination country’s requirements.',
    significance: 'Residence duration, physical presence, language, integration, criminal history, taxes, and treatment of existing citizenship vary by country.',
    example: 'Permanent residence may be one milestone toward eligibility, but it does not automatically convert into citizenship when a card expires.',
    source: { label: 'U.S. Department of State — Dual Nationality', url: 'https://travel.state.gov/content/travel/en/legal/travel-legal-considerations/Advice-about-Possible-Loss-of-US-Nationality-Dual-Nationality/Dual-Nationality.html' },
  },
];

export const GLOSSARY_CATEGORIES = [
  'Visas & residency',
  'Documents & applications',
  'U.S. tax & reporting',
  'Healthcare & benefits',
  'Moving & arrival',
] as const;
