import z from "zod";

export const AssessmentSchema = z.object({
  user_age: z.number().min(18).max(100),
  user_job: z.string().min(1),
  monthly_budget: z.number().min(100).max(50000),
  preferred_country: z.string().min(1),
  preferred_city: z.string().optional(),
  location_preference: z.enum(['beachside', 'rural', 'city']),
  climate_preference: z.enum(['tropical', 'seasonal', 'dry', 'mediterranean', 'temperate', 'northern']).optional(),
  immigration_policies_importance: z.number().min(0).max(5),
  healthcare_importance: z.number().min(0).max(5),
  safety_importance: z.number().min(0).max(5),
  internet_importance: z.number().min(0).max(5),
  emigration_process_importance: z.number().min(0).max(5),
  ease_of_immigration_importance: z.number().min(0).max(5),
  local_acceptance_importance: z.number().min(0).max(5),
});

export type AssessmentType = z.infer<typeof AssessmentSchema>;

export const AssessmentResultSchema = z.object({
  id: z.number(),
  overall_score: z.number().min(0).max(100),
  match_level: z.enum(['poor', 'good', 'very_good', 'perfect']),
  user_age: z.number(),
  user_job: z.string(),
  monthly_budget: z.number(),
  preferred_country: z.string(),
  preferred_city: z.string().nullable(),
  location_preference: z.string(),
  climate_preference: z.string(),
  immigration_policies_importance: z.number(),
  healthcare_importance: z.number(),
  safety_importance: z.number(),
  internet_importance: z.number(),
  emigration_process_importance: z.number(),
  ease_of_immigration_importance: z.number(),
  local_acceptance_importance: z.number(),
  criteriaScores: z.record(z.string(), z.number()).optional(),
  budget_compatibility: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string(),
});

export type AssessmentResultType = z.infer<typeof AssessmentResultSchema>;

export const CountryData = {
  countries: [
    'Portugal', 'Spain', 'Mexico', 'Costa Rica', 'Panama', 'Ecuador', 'Colombia',
    'Brazil', 'Argentina', 'Chile', 'Uruguay', 'Thailand', 'Malaysia', 'Philippines',
    'Vietnam', 'Japan', 'South Korea', 'Singapore', 'Australia', 'New Zealand',
    'Canada', 'United Kingdom', 'Ireland', 'Germany', 'France', 'Italy', 'Netherlands',
    'Denmark', 'Sweden', 'Norway', 'Finland', 'Switzerland', 'Austria', 'Belgium',
    'Ghana', 'Liberia', 'Nigeria', 'Morocco', 'Algeria', 'Angola', 'Antigua and Barbuda',
    'Aruba', 'Bahamas', 'Bangladesh', 'Barbados', 'Belize', 'Bolivia', 'Cameroon', 'China',
    'Côte d\'Ivoire', 'Cuba', 'Czech Republic', 'Dominican Republic', 'DR Congo', 'Egypt',
    'Ethiopia', 'Greece', 'Grenada', 'Haiti', 'Hungary', 'India', 'Indonesia', 'Jamaica',
    'Kenya', 'Pakistan', 'Paraguay', 'Peru', 'Poland', 'Puerto Rico', 'Romania', 'Saint Lucia',
    'Saudi Arabia', 'Senegal', 'South Africa', 'Sri Lanka', 'St. Thomas', 'Sudan', 'Tanzania',
    'Trinidad and Tobago', 'Turkey', 'UAE', 'Uganda', 'Ukraine', 'Venezuela', 'Zimbabwe',
    'Croatia', 'Cyprus', 'Malta', 'Estonia', 'Latvia', 'Lithuania', 'Slovenia', 'Slovakia',
    'Bulgaria', 'Luxembourg', 'Iceland', 'Montenegro', 'Albania', 'Saint Kitts and Nevis',
    'Dominica', 'Saint Vincent and the Grenadines', 'Cayman Islands', 'Curaçao',
    'Turks and Caicos Islands', 'Sint Maarten', 'British Virgin Islands'
  ],
  cities: {
    'Portugal': ['Lisbon', 'Porto', 'Faro', 'Braga', 'Coimbra'],
    'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Bilbao'],
    'Mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Cancun', 'Puerto Vallarta'],
    'Costa Rica': ['San José', 'Manuel Antonio', 'Tamarindo', 'Monteverde', 'Jaco'],
    'Panama': ['Panama City', 'Boquete', 'San Carlos', 'El Valle', 'Bocas del Toro'],
    'Ecuador': ['Quito', 'Cuenca', 'Guayaquil', 'Salinas', 'Manta'],
    'Colombia': ['Bogotá', 'Medellín', 'Cartagena', 'Cali', 'Santa Marta'],
    'Brazil': ['São Paulo', 'Rio de Janeiro', 'Salvador', 'Brasília', 'Florianópolis'],
    'Argentina': ['Buenos Aires', 'Mendoza', 'Córdoba', 'Bariloche', 'Salta'],
    'Chile': ['Santiago', 'Valparaíso', 'La Serena', 'Puerto Montt', 'Antofagasta'],
    'Uruguay': ['Montevideo', 'Punta del Este', 'Colonia del Sacramento', 'Maldonado'],
    'Thailand': ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Hua Hin'],
    'Malaysia': ['Kuala Lumpur', 'Penang', 'Johor Bahru', 'Kota Kinabalu', 'Malacca'],
    'Philippines': ['Manila', 'Cebu', 'Davao', 'Baguio', 'Iloilo'],
    'Vietnam': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hoi An', 'Nha Trang'],
    'Japan': ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Hiroshima'],
    'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Jeju'],
    'Singapore': ['Singapore'],
    'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'],
    'New Zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga'],
    'Canada': ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa'],
    'United Kingdom': ['London', 'Edinburgh', 'Manchester', 'Liverpool', 'Bristol'],
    'Ireland': ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford'],
    'Germany': ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne'],
    'France': ['Paris', 'Lyon', 'Marseille', 'Nice', 'Toulouse'],
    'Italy': ['Rome', 'Milan', 'Naples', 'Florence', 'Venice'],
    'Netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven'],
    'Denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
    'Sweden': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås'],
    'Norway': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen'],
    'Finland': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Turku'],
    'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne'],
    'Austria': ['Vienna', 'Salzburg', 'Innsbruck', 'Graz', 'Linz'],
    'Belgium': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège'],
    'Ghana': ['Accra', 'Kumasi', 'Tamale', 'Cape Coast', 'Sekondi-Takoradi'],
    'Liberia': ['Monrovia', 'Gbarnga', 'Buchanan', 'Kakata', 'Voinjama'],
    'Nigeria': ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt'],
    'Morocco': ['Casablanca', 'Rabat', 'Marrakech', 'Fez', 'Tangier'],
    'Algeria': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'],
    'Angola': ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Lubango'],
    'Antigua and Barbuda': ['St. John\'s', 'All Saints', 'Liberta', 'Potter\'s Village', 'Bolans'],
    'Aruba': ['Oranjestad', 'Noord', 'San Nicolaas', 'Paradera', 'Santa Cruz'],
    'Bahamas': ['Nassau', 'Freeport', 'West End', 'Coopers Town', 'Marsh Harbour'],
    'Bangladesh': ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet'],
    'Barbados': ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba', 'Holetown'],
    'Belize': ['Belize City', 'San Ignacio', 'Belmopan', 'San Pedro', 'Orange Walk'],
    'Bolivia': ['Santa Cruz', 'La Paz', 'Cochabamba', 'El Alto', 'Sucre'],
    'Cameroon': ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua'],
    'China': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu'],
    'Côte d\'Ivoire': ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'San-Pédro'],
    'Cuba': ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara'],
    'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec'],
    'Dominican Republic': ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís', 'Higüey'],
    'DR Congo': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani'],
    'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said'],
    'Ethiopia': ['Addis Ababa', 'Dire Dawa', 'Mek\'ele', 'Gondar', 'Bahir Dar'],
    'Greece': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa'],
    'Grenada': ['St. George\'s', 'Gouyave', 'Grenville', 'Victoria', 'Sauteurs'],
    'Haiti': ['Port-au-Prince', 'Carrefour', 'Delmas', 'Pétion-Ville', 'Cité Soleil'],
    'Hungary': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs'],
    'India': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai'],
    'Indonesia': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Bekasi'],
    'Jamaica': ['Kingston', 'Spanish Town', 'Portmore', 'Montego Bay', 'Mandeville'],
    'Kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
    'Pakistan': ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Islamabad'],
    'Paraguay': ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá'],
    'Peru': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura'],
    'Poland': ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań'],
    'Puerto Rico': ['San Juan', 'Bayamón', 'Carolina', 'Ponce', 'Caguas'],
    'Romania': ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța'],
    'Saint Lucia': ['Castries', 'Gros Islet', 'Soufrière', 'Vieux Fort', 'Dennery'],
    'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam'],
    'Senegal': ['Dakar', 'Touba', 'Thiès', 'Kaolack', 'Saint-Louis'],
    'South Africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth'],
    'Sri Lanka': ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Sri Jayawardenepura Kotte', 'Negombo'],
    'St. Thomas': ['Charlotte Amalie', 'Anna\'s Retreat', 'Tutu', 'Red Hook', 'Cruz Bay'],
    'Sudan': ['Khartoum', 'Omdurman', 'Khartoum North', 'Port Sudan', 'Kassala'],
    'Tanzania': ['Dar es Salaam', 'Mwanza', 'Zanzibar City', 'Arusha', 'Dodoma'],
    'Trinidad and Tobago': ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima', 'Point Fortin'],
    'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya'],
    'UAE': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman'],
    'Uganda': ['Kampala', 'Nansana', 'Kira', 'Ssabagabo', 'Mbarara'],
    'Ukraine': ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk'],
    'Venezuela': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay'],
    'Zimbabwe': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Epworth'],
    'Croatia': ['Zagreb', 'Split', 'Dubrovnik', 'Rijeka', 'Zadar'],
    'Cyprus': ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta'],
    'Malta': ['Valletta', 'Birkirkara', 'Sliema', 'St. Julian\'s', 'Bugibba'],
    'Estonia': ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve'],
    'Latvia': ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala'],
    'Lithuania': ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
    'Slovenia': ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje'],
    'Slovakia': ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra'],
    'Bulgaria': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse'],
    'Luxembourg': ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck'],
    'Iceland': ['Reykjavík', 'Kópavogur', 'Hafnarfjörður', 'Akureyri', 'Reykjanesbær'],
    'Montenegro': ['Podgorica', 'Nikšić', 'Herceg Novi', 'Pljevlja', 'Budva'],
    'Albania': ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Elbasan'],
    'Saint Kitts and Nevis': ['Basseterre', 'Charlestown', 'Sadlers', 'Cayon', 'Sandy Point Town'],
    'Dominica': ['Roseau', 'Portsmouth', 'Marigot', 'Berekua', 'Mahaut'],
    'Saint Vincent and the Grenadines': ['Kingstown', 'Georgetown', 'Byera Village', 'Biabou', 'Port Elizabeth'],
    'Cayman Islands': ['George Town', 'West Bay', 'Bodden Town', 'East End', 'North Side'],
    'Curaçao': ['Willemstad', 'Sint Michiel', 'Barber', 'Dorp Soto', 'Newport'],
    'Turks and Caicos Islands': ['Cockburn Town', 'Providenciales', 'Balfour Town', 'Kew', 'Whitby'],
    'Sint Maarten': ['Philipsburg', 'Lower Prince\'s Quarter', 'Cul de Sac', 'Cole Bay', 'Marigot'],
    'British Virgin Islands': ['Road Town', 'Spanish Town', 'The Settlement', 'Great Harbour', 'East End-Long Look']
  }
};
